sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - REGISTRY_USER=vektory79
    - secure: cOEY80cD02KzmMwAevGlY/nCEYASVwQ/LFrDlqo+Anq/8Mlwj/Y40i2I678T2uvSfkADUMJF+Fx1obaOgIVErFMjSOt8fvGwCvHv/mPt9q5v8Pg3iWRXLTGcUtuUZTUYr7zsGR2Qzu5mcXd/iaorkJXLGQl01Hmp8IjEwLaft+MRCRt2/6UOLvCpuSNoSmxMEoo0bobyb3oLNgqgo+7nRq9sxo+VpQ7hQi4mIVOHwCXkPOzQdbDiQJc3kjFbGGEJzmtCuV970gJXZQ2FJgZvE8oBe9alxPkSzQFDbSRjznuPa8BwQDdowbM1R2hAKkbmRcP35HzisoIWb60J1Hf967aqdkSUCnGXElNIcABqKQC2MpgFw4a4QEX/LSrvRqaS7cHHftEWliu6V4QGpy7JrYXFSsQJpypjDWgHW0e9nAGxwmZsyNjARloZLN+nesMqqNOpuW3SLfLxZFo0cDynE6tYpQlBQUxwFKQXS/igBkEFAsAMK/X2nqtY6K5s1o7PV8w2abEbb+cCIAtBnSU/B3CgF2yGy4eGBc8TRUCIbDL1RXMfY2gdK/c7X/coyiz6RBDbGZyubycoCSzl4Uao2v/9l3UtfnbkG2Nbo8/02h96EBwkRCKZNmdbxA25aZN9WPAW+QdRhjUA9A2xmUmDkLUtDHgFov8jZ00KxAkRR0A=
script:
  - ./build.sh -pc

after_script:
  - docker images
before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin javister-docker-docker.bintray.io

deploy:
  provider: script
  script: ./build.sh -rdc
  on:
    branch: master
